from __future__ import annotations

from pathlib import Path

BEGIN_MARKER = "<!-- context-compiler:begin -->"
END_MARKER = "<!-- context-compiler:end -->"

BASE_GUIDANCE = (
    "Read `.context/index.md` first.\n"
    "Then read only the relevant `.context/*.md` file before exploring source.\n"
    "Avoid broad repo scans unless the context artifacts are missing or stale."
)

_CLAUDE_BODY = (
    "## Context Compiler\n"
    "\n"
    "This repository ships precompiled context artifacts under `.context/`.\n"
    "\n"
    f"{BASE_GUIDANCE}\n"
    "\n"
    "Run `context-compiler scan` to rebuild the artifacts and "
    "`context-compiler doctor` to check freshness."
)

_AGENTS_BODY = (
    "## Agents guidance\n"
    "\n"
    f"{BASE_GUIDANCE}\n"
    "\n"
    "Artifacts live in `.context/`. Rebuild with `context-compiler scan`."
)

_CODEX_BODY = (
    "## Codex instructions\n"
    "\n"
    f"{BASE_GUIDANCE}\n"
    "\n"
    "See `.context/index.md` for the reading order."
)

_COPILOT_BODY = (
    "## Copilot instructions\n"
    "\n"
    f"{BASE_GUIDANCE}\n"
    "\n"
    "Artifacts are regenerated by `context-compiler scan`."
)

INSTRUCTION_FILES: tuple[tuple[str, str], ...] = (
    ("CLAUDE.md", _CLAUDE_BODY),
    ("AGENTS.md", _AGENTS_BODY),
    ("codex.md", _CODEX_BODY),
    (".github/copilot-instructions.md", _COPILOT_BODY),
)


def write_instruction_files(repo_root: Path) -> list[Path]:
    written: list[Path] = []
    for relative, body in INSTRUCTION_FILES:
        path = repo_root / relative
        path.parent.mkdir(parents=True, exist_ok=True)
        existing = path.read_text(encoding="utf-8") if path.exists() else ""
        updated = _apply_managed_block(existing, body)
        path.write_text(updated, encoding="utf-8")
        written.append(path)
    return written


def _apply_managed_block(existing: str, body: str) -> str:
    block = f"{BEGIN_MARKER}\n{body}\n{END_MARKER}"
    if BEGIN_MARKER in existing and END_MARKER in existing:
        before, _, rest = existing.partition(BEGIN_MARKER)
        _, _, after = rest.partition(END_MARKER)
        stitched = before + block + after
        if not stitched.endswith("\n"):
            stitched += "\n"
        return stitched
    if existing.strip() == "":
        return block + "\n"
    separator = "" if existing.endswith("\n") else "\n"
    return existing + separator + "\n" + block + "\n"
